const Vue = require('vue');
const VueRouter = require('vue-router');

Vue.use(VueRouter);
let routes = [
    {
        name:'gallery',
        path:'/gallery',
        component:require('./../../vue/pages/gallery.vue')
    },
    {
        name:'blog',
        path:'/blog',
        component:require('./../../vue/pages/blog.vue')
    },
    {
        name:'newProducts',
        path:'/newProducts',
        component:require('./../../vue/pages/newProducts.vue')
    },
    {
        name:'subcategory',
        path:'/subcategory:id',
        component:require('./../../vue/pages/subcategory.vue')
    },
    {
        name:'listProducts',
        path:'/listProducts:id&:subid',
        component:require('./../../vue/pages/listProducts.vue')
    },
    {
        name:'product',
        path:'/product&:code',
        component:require('./../../vue/pages/product.vue')
    },
    {
        name:'hit',
        path:'/hit',
        component:require('./../../vue/pages/hit.vue')
    },
    {
        name:'recommend',
        path:'/recommend',
        component:require('./../../vue/pages/recommend.vue')
    },
    {
        name:'popular',
        path:'/popular',
        component:require('./../../vue/pages/popular.vue')
    },
    {
        name:'sales',
        path:'/sales',
        component:require('./../../vue/pages/sales.vue')
    },
    {
        name:'discounts',
        path:'/discounts',
        component:require('./../../vue/pages/discounts.vue')
    },
    {
        name:'slider',
        path:'/slider',
        component:require('./../../vue/pages/slider.vue')
    },
    {
        name:'promotions',
        path:'/promotions',
        component:require('./../../vue/pages/promotions.vue')
    },
    {
        name:'brand',
        path:'/brand',
        component:require('./../../vue/pages/brand.vue')
    },
]

module.exports = new VueRouter ({
    mode:'history',
    routes:routes
})
